### ISSUE TITLE
Crash on importing lib

### ISSUE THREAD

**Issue by fxhereng** [ilansas/react-native-navigation-drawer#13]
The app crashes on putting (anywhere in my code) the require line:

``` javascript
var SlideMenu = require('react-native-navigation-drawer');
```

I'm trying to import a screenshot of the error but it's not working properly..... The error says "undefined is not an object (evaluating '_reactNative.Dimensions.get')

I'm using react native 0.17.

![Uploading bug-nav-drawer.png…]()

Best regards,

**Comment by L-Jovi** [comment]
@fxhereng  the same issue, maybe author have less time to fix, I suggest that you could try [this project](https://github.com/react-native-fellowship/react-native-side-menu).

**Comment by MaddyMastering** [comment]
Getting this error 

Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: Inspector
  Paths: /home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/react-native-navigation-drawer/node_modules/react-native/Libraries/Inspector.js collides with /home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/react-native/Libraries/Inspector/Inspector.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: Inspector
  Paths: /home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/react-native-navigation-drawer/node_modules/react-native/Libraries/Inspector.js collides with /home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/react-native/Libraries/Inspector/Inspector.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:160:15)
    at /home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:125:25
    at run (/home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:14:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
