### ISSUE TITLE
Getting this error plz help.

### ISSUE THREAD

**Issue by MaddyMastering** [ilansas/react-native-navigation-drawer#15]
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: Inspector
  Paths: /home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/react-native-navigation-drawer/node_modules/react-native/Libraries/Inspector.js collides with /home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/react-native/Libraries/Inspector/Inspector.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: Inspector
  Paths: /home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/react-native-navigation-drawer/node_modules/react-native/Libraries/Inspector.js collides with /home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/react-native/Libraries/Inspector/Inspector.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:160:15)
    at /home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:125:25
    at run (/home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/home/maddy/Maddy/Projects/JavaScript/react_native/demo/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:14:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by veris-ravindra** [comment]
Im tooo getting the same error either its some import or donno

**Comment by vimask** [comment]
i have the same problem, hope the author resolves this soon

**Comment by EgaSetya** [comment]
I have the same issue too afer updating my react native. Do you guys find the solution for this?
